import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"
import "./globals.css"
import Header from "./components/Header";
import { Suspense } from "react";
import LoadingSpinner from "./components/Loading";
import { AuthProvider } from "./lib/auth/provider";
import Providers from "./providers";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  // 日本語フォントを使用するためにweight設定を追加
  weight: ["400", "500", "700"],
  // 必要に応じてpreloadを追加（日本語の場合は多くの文字があるため）
  preload: false
})

export const metadata: Metadata = {
  title: "Book Commerce",
  description: "Generated by create next app",
};

/**
 * ルートレイアウト
 *
 * - HTMLのroot要素
 * - Noto Sans JPフォントを適用
 * - Next-Authのプロバイダーを適用
 * - Headerコンポーネントを表示
 * - Suspenseコンポーネントを使用して、childrenを fallback=<LoadingSpinner />でwrapping
 * - Next-Authのプロバイダーで、認証情報を childrenに渡す
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} antialiased`}
      >
        <Providers>

          <AuthProvider>
            <Header />
            <div className="pt-20">
              <Suspense fallback={<LoadingSpinner />}>
                {children}
              </Suspense>
            </div>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
