import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"
import "./globals.css"
import Header from "./components/Header";
import { NextAuthProvider } from "./lib/next-auth/provider";
import { Suspense } from "react";
import LoadingSpinner from "./components/Loading";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  // 日本語フォントを使用するためにweight設定を追加
  weight: ["400", "500", "700"],
  // 必要に応じてpreloadを追加（日本語の場合は多くの文字があるため）
  preload: false
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Book Commerce",
  description: "Generated by create next app",
};

/**
 * ルートレイアウト
 *
 * - HTMLのroot要素
 * - Noto Sans JPフォントを適用
 * - Next-Authのプロバイダーを適用
 * - Headerコンポーネントを表示
 * - Suspenseコンポーネントを使用して、childrenを fallback=<LoadingSpinner />でwrapping
 * - Next-Authのプロバイダーで、認証情報を childrenに渡す
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} antialiased`}
      >
        <NextAuthProvider>
          <Header />
          <Suspense fallback={<LoadingSpinner />}>
            {children}
          </Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
